In [1]:
pip install pandas


Note: you may need to restart the kernel to use updated packages.


In [74]:
import pandas as pd
import numpy as np

In [76]:
A=np.array([1,2,3,4,5])
B=np.array([1,4,6,3,5])
print(A)
print(B)
C=np.where(A==B)
print(C)

[1 2 3 4 5]
[1 4 6 3 5]
(array([0, 4], dtype=int64),)


In [15]:
df=pd.read_excel('1.xlsx')

In [34]:
pd.read_excel('1.xlsx')

index      company   body-style  wheel-base  length engine-type  \
0       0  alfa-romero  convertible        88.6   168.8        dohc   
1       1  alfa-romero  convertible        88.6   168.8        dohc   
2       2  alfa-romero    hatchback        94.5   171.2        ohcv   
3       3         audi        sedan        99.8   176.6         ohc   
4       4         audi        sedan        99.4   176.6         ohc   
..    ...          ...          ...         ...     ...         ...   
56     81   volkswagen        sedan        97.3   171.7         ohc   
57     82   volkswagen        sedan        97.3   171.7         ohc   
58     86   volkswagen        sedan        97.3   171.7         ohc   
59     87        volvo        sedan       104.3   188.8         ohc   
60     88        volvo        wagon       104.3   188.8         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
0              four         111               21  13495.0  
1              four         111               21  16500.0  
2               six         154               19  16500.0  
3              four         102               24  13950.0  
4              five         115               18  17450.0  
..              ...         ...              ...      ...  
56             four          85               27   7975.0  
57             four          52               37   7995.0  
58             four         100               26   9995.0  
59             four         114               23  12940.0  
60             four         114               23  13415.0  

[61 rows x 10 columns]

In [16]:
df.head()

index      company   body-style  wheel-base  length engine-type  \
0      0  alfa-romero  convertible        88.6   168.8        dohc   
1      1  alfa-romero  convertible        88.6   168.8        dohc   
2      2  alfa-romero    hatchback        94.5   171.2        ohcv   
3      3         audi        sedan        99.8   176.6         ohc   
4      4         audi        sedan        99.4   176.6         ohc   

  num-of-cylinders  horsepower  average-mileage    price  
0             four         111               21  13495.0  
1             four         111               21  16500.0  
2              six         154               19  16500.0  
3             four         102               24  13950.0  
4             five         115               18  17450.0

In [17]:
df.tail()

index     company body-style  wheel-base  length engine-type  \
56     81  volkswagen      sedan        97.3   171.7         ohc   
57     82  volkswagen      sedan        97.3   171.7         ohc   
58     86  volkswagen      sedan        97.3   171.7         ohc   
59     87       volvo      sedan       104.3   188.8         ohc   
60     88       volvo      wagon       104.3   188.8         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
56             four          85               27   7975.0  
57             four          52               37   7995.0  
58             four         100               26   9995.0  
59             four         114               23  12940.0  
60             four         114               23  13415.0

In [38]:
 df.columns

Index(['index', 'company', 'body-style', 'wheel-base', 'length', 'engine-type',
       'num-of-cylinders', 'horsepower', 'average-mileage', 'price'],
      dtype='object')

In [72]:
df.nunique()

index               58
company             16
body-style           5
wheel-base          26
length              35
engine-type          6
num-of-cylinders     7
horsepower          29
average-mileage     21
price               57
dtype: int64

In [25]:
df.isnull().sum()

index               0
company             0
body-style          0
wheel-base          0
length              0
engine-type         0
num-of-cylinders    0
horsepower          0
average-mileage     0
price               3
dtype: int64

In [36]:
data=df.drop(['wheel-base','length'],axis=1)

In [37]:
df.dropna(subset=df.columns,inplace=True)

In [49]:
new=df.sort_values(by='price')
new.tail(1)


index        company body-style  wheel-base  length engine-type  \
35     47  mercedes-benz    hardtop       112.0   199.2        ohcv   

   num-of-cylinders  horsepower  average-mileage    price  
35            eight         184               14  45400.0

In [40]:
df.max()

index                    88
company               volvo
body-style            wagon
wheel-base            120.9
length                208.1
engine-type           rotor
num-of-cylinders        two
horsepower              262
average-mileage          47
price               45400.0
dtype: object

In [51]:
new2=df.sort_values(by='company')

In [61]:
df.groupby('company').count()

index  body-style  wheel-base  length  engine-type  \
company                                                             
alfa-romero        3           3           3       3            3   
audi               4           4           4       4            4   
bmw                6           6           6       6            6   
chevrolet          3           3           3       3            3   
dodge              2           2           2       2            2   
honda              3           3           3       3            3   
isuzu              1           1           1       1            1   
jaguar             3           3           3       3            3   
mazda              5           5           5       5            5   
mercedes-benz      4           4           4       4            4   
mitsubishi         4           4           4       4            4   
nissan             5           5           5       5            5   
porsche            2           2           2       2            2   
toyota             7           7           7       7            7   
volkswagen         4           4           4       4            4   
volvo              2           2           2       2            2   

               num-of-cylinders  horsepower  average-mileage  price  
company                                                              
alfa-romero                   3           3                3      3  
audi                          4           4                4      4  
bmw                           6           6                6      6  
chevrolet                     3           3                3      3  
dodge                         2           2                2      2  
honda                         3           3                3      3  
isuzu                         1           1                1      1  
jaguar                        3           3                3      3  
mazda                         5           5                5      5  
mercedes-benz                 4           4                4      4  
mitsubishi                    4           4                4      4  
nissan                        5           5                5      5  
porsche                       2           2                2      2  
toyota                        7           7                7      7  
volkswagen                    4           4                4      4  
volvo                         2           2                2      2

In [65]:
df[df['company']=='toyota']

index company body-style  wheel-base  length engine-type num-of-cylinders  \
48     66  toyota  hatchback        95.7   158.7         ohc             four   
49     67  toyota  hatchback        95.7   158.7         ohc             four   
50     68  toyota  hatchback        95.7   158.7         ohc             four   
51     69  toyota      wagon        95.7   169.7         ohc             four   
52     70  toyota      wagon        95.7   169.7         ohc             four   
53     71  toyota      wagon        95.7   169.7         ohc             four   
54     79  toyota      wagon       104.5   187.8        dohc              six   

    horsepower  average-mileage    price  
48          62               35   5348.0  
49          62               31   6338.0  
50          62               31   6488.0  
51          62               31   6918.0  
52          62               27   7898.0  
53          62               27   8778.0  
54         156               19  15750.0

In [70]:
new3=df.sort_values(by='price',ascending=False)
new3.head()

index        company   body-style  wheel-base  length engine-type  \
35     47  mercedes-benz      hardtop       112.0   199.2        ohcv   
11     14            bmw        sedan       103.5   193.8         ohc   
34     46  mercedes-benz        sedan       120.9   208.1        ohcv   
46     62        porsche  convertible        89.5   168.9        ohcf   
12     15            bmw        sedan       110.0   197.0         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
35            eight         184               14  45400.0  
11              six         182               16  41315.0  
34            eight         184               14  40960.0  
46              six         207               17  37028.0  
12              six         182               15  36880.0